version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: linkup_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - linkup_data:/var/lib/postgresql/data

volumes:
  linkup_data: